app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/posts', function () {
    return view('admin.posts');
});

Route::get('api/calendar/get-all-events','CalendarController@getCalendarEvents');

Route::get('admin/login', function () {
    return view('auth.login');
});

Route::group(['prefix' => 'admin','middleware' => 'auth'], function() {

    Route::get('/','HomeController@index');
    Route::get('subscribers','SubscribeController@show');

    Route::get('home', 'HomeController@index');
    Route::post('home/update', 'HomeController@updateHome');
    Route::get('home/featured', 'HomeController@featured');
    Route::get('home/footer', 'HomeController@footer');
    Route::post('home/footer', 'HomeController@updateFooter');
    Route::get('home/menu', 'HomeController@menu');
    Route::post('home/menu', 'HomeController@updateMenu');
    Route::get('home/create/featured', 'HomeController@createFeatured');
    Route::post('home/featured/post', 'HomeController@storeFeatured');
    Route::get('home/landing', 'HomeController@landing');
    Route::post('home/landing/create', 'HomeController@saveLandingElement');
    Route::post('home/landing/update', 'HomeController@updateLandingElement');
    Route::get('home/landing/{id}/delete', 'HomeController@deleteLandingElement');
    Route::get('home/landing/{id}/edit', 'HomeController@editLandingElement');
    Route::get('home/create/landing', 'HomeController@createLandingElement');

    Route::get('web-pages', 'Admin\PageController@show');
    Route::get('create/web-pages', 'Admin\PageController@create');
    Route::get('web-pages/{id}/edit', 'Admin\PageController@edit');
    Route::get('pages/{id}/delete', 'Admin\PageController@delete');
    Route::post('pages', 'Admin\PageController@post');
    Route::post('pages/update', 'Admin\PageController@update');

    Route::get('forms', 'Admin\FormController@index');
    Route::get('create/forms', 'Admin\FormController@create');
    Route::get('forms/entries/{id}', 'Admin\FormController@showEntries');
    Route::get('forms/entries/items/{id}', 'Admin\FormController@showEntryItems');
    Route::get('forms/preview/{id}', 'Admin\FormController@preview');
    Route::get('forms/show/{id}', 'Admin\FormController@show');
    Route::get('forms/{id}/delete', 'Admin\FormController@delete');
    Route::post('forms', 'Admin\FormController@store');
    Route::post('forms/update', 'Admin\FormController@update');

    Route::get('create/contributors', 'Admin\ContributorController@create');
    Route::get('contributors/{id}/edit', 'Admin\ContributorController@edit');
    Route::get('posts/contributors', 'Admin\ContributorController@show');
    Route::post('create/contributors', 'Admin\ContributorController@store');
    Route::post('update/contributors', 'Admin\ContributorController@update');
    Route::get('contributors/order', 'Admin\ContributorController@order');
    Route::post('contributors/order', 'Admin\ContributorController@orderUpdate');

    Route::get('posts/create/{slug}', 'PostController@create');
    Route::post('posts/', 'PostController@post');
    Route::get('posts/{id}/edit', 'PostController@edit');
    Route::get('posts/{id}/delete', 'PostController@delete');
    Route::get('posts/{slug}', 'PostController@show');
    Route::post('posts/update', 'PostController@update');

    Route::get('create/presskits/', 'Admin\PresskitController@create');
    Route::get('presskits/', 'Admin\PresskitController@show');
    Route::post('presskits/', 'Admin\PresskitController@store');
    Route::get('presskits/{id}/edit', 'Admin\PresskitController@edit');
    Route::get('presskits/{id}/delete', 'Admin\PresskitController@delete');
    Route::get('presskits/{slug}', 'Admin\PresskitController@show');
    Route::post('presskits/update', 'Admin\PresskitController@update');

    Route::get('create/publications/', 'Admin\PublicationController@create');
    Route::get('publications/', 'Admin\PublicationController@show');
    Route::post('publications/', 'Admin\PublicationController@store');
    Route::get('publications/{id}/edit', 'Admin\PublicationController@edit');
    Route::get('publications/{id}/delete', 'Admin\PublicationController@delete');
    Route::get('publications/{slug}', 'Admin\PublicationController@show');
    Route::post('publications/update', 'Admin\PublicationController@update');

    Route::get('create/podcasts/', 'Admin\PodcastController@create');
    Route::get('podcasts/', 'Admin\PodcastController@show');
    Route::post('podcasts/', 'Admin\PodcastController@store');
    Route::get('podcasts/{id}/edit', 'Admin\PodcastController@edit');
    Route::get('podcasts/{id}/delete', 'Admin\PodcastController@delete');
    Route::get('podcasts/{slug}', 'Admin\PodcastController@show');
    Route::post('podcasts/update', 'Admin\PodcastController@update');

    Route::get('create/materials/', 'Admin\MaterialController@create');
    Route::get('materials/', 'Admin\MaterialController@show');
    Route::post('materials/', 'Admin\MaterialController@store');
    Route::get('materials/{id}/edit', 'Admin\MaterialController@edit');
    Route::get('materials/{id}/delete', 'Admin\MaterialController@delete');

    Route::get('create/materials/videos', 'Admin\MaterialController@createVideo');
    Route::get('materials/videos', 'Admin\MaterialController@showVideos');

    Route::get('create/materials/open-calls', 'Admin\MaterialController@createOpenCall');
    Route::get('create/materials/videos2', 'Admin\MaterialController@createOpenCall');

    Route::get('materials/open-calls', 'Admin\MaterialController@showOpenCalls');
    Route::get('materials/videos2', 'Admin\MaterialController@showOpenCalls');

    Route::get('materials/series-contents', 'Admin\MaterialContentController@get');
    Route::post('materials/series-contents', 'Admin\MaterialContentController@update');

    Route::get('materials/{slug}', 'Admin\MaterialController@show');
    Route::post('materials/update', 'Admin\MaterialController@update');

    Route::get('create/spaces/', 'Admin\SpacesController@create');
    Route::get('spaces/', 'Admin\SpacesController@show');
    Route::post('spaces/', 'Admin\SpacesController@store');
    Route::get('spaces/{id}/edit', 'Admin\SpacesController@edit');
    Route::get('spaces/{id}/delete', 'Admin\SpacesController@delete');
    Route::get('spaces/{slug}', 'Admin\SpacesController@show');
    Route::post('spaces/update', 'Admin\SpacesController@update');

    Route::get('create/stores/workshops', 'Admin\StoreWorkshopController@create');
    Route::get('stores/workshops', 'Admin\StoreWorkshopController@show');
    Route::post('stores/workshops', 'Admin\StoreWorkshopController@store');
    Route::get('stores/workshops/{id}/edit', 'Admin\StoreWorkshopController@edit');
    Route::get('stores/workshops/{id}/delete', 'Admin\StoreWorkshopController@delete');
    Route::get('stores/workshops/{slug}', 'Admin\StoreWorkshopController@show');
    Route::post('stores/workshops/update', 'Admin\StoreWorkshopController@update');

    Route::get('create/stores/', 'Admin\StoreController@create');
    Route::get('stores/', 'Admin\StoreController@show');
    Route::post('stores/', 'Admin\StoreController@store');
    Route::get('stores/{id}/edit', 'Admin\StoreController@edit');
    Route::get('stores/{id}/delete', 'Admin\StoreController@delete');
    Route::get('stores/{slug}', 'Admin\StoreController@show');
    Route::post('stores/update', 'Admin\StoreController@update');


    Route::get('create/triennial-2023/', 'Admin\Triennial2023Controller@create');
    Route::get('triennial-2023/', 'Admin\Triennial2023Controller@index');
    Route::post('triennial-2023/', 'Admin\Triennial2023Controller@store');
    Route::get('triennial-2023/{id}/edit', 'Admin\Triennial2023Controller@edit');
    Route::get('triennial-2023/{id}/delete', 'Admin\Triennial2023Controller@delete');
    Route::get('triennial-2023/{slug}', 'Admin\Triennial2023Controller@show');
    Route::post('triennial-2023/update', 'Admin\Triennial2023Controller@update');

    Route::get('create/tours/', 'Admin\SatTourController@create');
    Route::get('tours/', 'Admin\SatTourController@show');
    Route::post('tours/', 'Admin\SatTourController@store');
    Route::get('tours/{id}/edit', 'Admin\SatTourController@edit');
    Route::get('tours/{id}/delete', 'Admin\SatTourController@delete');
    Route::get('tours/{slug}', 'Admin\SatTourController@show');
    Route::post('tours/update', 'Admin\SatTourController@update');

    Route::group(['prefix' => 'research'], function() {

        Route::group(['prefix' => 'types'], function() {
            Route::get('/', 'Admin\ResearchController@types');
            Route::get('create', 'Admin\ResearchController@createType');
            Route::post('/', 'Admin\ResearchController@storeType');
            Route::get('edit/{id}', 'Admin\ResearchController@editType');
            Route::get('delete/{id}', 'Admin\ResearchController@deleteType');
            Route::post('update', 'Admin\ResearchController@updateType');
        });

        Route::group(['prefix' => 'feedback'], function() {
            Route::get('/', 'Admin\ResearchController@showFeedbacks');
            Route::get('/{id}', 'Admin\ResearchController@viewFeedback');
        });

        Route::group(['prefix' => 'buildings'], function() {
            Route::get('/', 'Admin\ResearchController@buildings');
            Route::get('create', 'Admin\ResearchController@createBuilding');
            Route::post('', 'Admin\ResearchController@storeBuilding');

app/Models/Page.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Nicolaslopezj\Searchable\SearchableTrait;

class Page extends Model
{
    use SearchableTrait;

    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        /**
         * Columns and their priority in search results.
         * Columns with higher values are more important.
         * Columns with equal values have equal importance.
         *
         * @var array
         */
        'columns' => [
            'name' => 10,
            'name_ar' => 10,
            'content' => 1,
            'content_ar' => 1,
            'additional_content_top' => 1,
            'additional_content_bottom' => 1
        ]
    ];

    protected $fillable = [
        'name',
        'name_ar',
        'slug',
        'content',
        'content_ar',
        'publish_date',
        'page_type',
        'additional_content_top',
        'additional_content_bottom',
        'active',
        'created_at'
    ];

    public $timestamps = ['publish_date'];

    public function parent(){
        return $this->hasOne('App\Models\PageParent');
    }

    public function children(){
        return $this->hasMany('App\Models\PageParent','page_parent_id');
    }

    public function posts(){
        return $this->hasMany('App\Models\Post','page_id');
    }

    public function sliders(){
        return $this->hasMany('App\Models\PageImageSlide');
    }

    /**
     * An article has uploads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function forms()
    {
        return $this->morphOne('App\Models\PageForm', 'formable');
    }

    /**
     * An article has uploads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function buttonLinks()
    {
        return $this->morphOne('App\Models\ButtonLink', 'linkable');
    }

    public function getSlidersAttribute(){
        return $this->sliders()->get();
    }

    public function getSliderAttribute(){
        return $this->sliders()->first();
    }

    public function getParentAttribute(){
        $parent = $this->parent()->first();
        if($parent==null)
            return [];

        return $this->find($parent->page_parent_id);
    }

    public function getChildrenAttribute(){
        /** $childrenIds = $this->children()->get();

        if($childrenIds==null)
            return [];

        $children = [];

        foreach ($childrenIds as $childId)
            $children[] = $this->find($childId->page_id);

        return $children; **/
		
        $childrenIds = $this->children()->get();

        if($childrenIds==null)
            return [];

        $children = [];

        /** foreach ($childrenIds as $childId)
            $children[] = $this->find($childId->page_id); **/

		$ids = [];
        foreach ($childrenIds as $childId)
            $ids[] = $childId->page_id;

		$children = Page::whereIn('id',$ids)->orderBy('created_at',ASC)->get();

        return $children;
    }

    public function getBreadcrumbsAttribute(){
        $parents = [];
        $currentItem = $this;

        $parents[] = ['name'=>$this->name,'name_ar'=>$this->name_ar,'slug'=>$this->slug];

        while($currentItem->parent){
            $parents[] = ['name'=>$currentItem->parent->name,'name_ar'=>$currentItem->parent->name_ar,'slug'=>$currentItem->parent->slug];
            $currentItem = $currentItem->parent;
        }

        $parents[] = ['name'=>"Home",'name_ar'=>"الصفحة الرئيسية",'slug'=>"",'link'=>''];

        $parents = array_reverse($parents);
        $link = "";

        for($x=1;$x<count($parents);$x++){
            $link = $link."/".$parents[$x]['slug'];
            $parents[$x]['link'] = $link;
        }

        return $parents;
    }

    public function getLinkAttribute(){
        $link = "pages/";
        $currentItem = $this;

        while($this->parent){
            $link .= $currentItem->parent->slug.'/';

            if($currentItem->parent->parent)
                $currentItem = $currentItem->parent;
            else
                break;
        }

        $link .= $this->slug;
        return $link;
    }
}

resources/views/pages/contributors.blade.php
@extends('pages.master')

@section('content')

<div class="innerpage">
    <div class="container text-center">
        <div class="body-section contents with-img-header">
            <div class="row" dir="">
                <div class="col-md-6 text-left">
                    <div class="breadcrumbs en">
                        @include('partials.breadcrumbs')
                    </div>
                    <h1 class="en">{{ $page->name }}</h1>
                    {!! $page->content !!}
                    <br/>
                </div>
                <div class="col-md-6 text-right">
                    <div class="breadcrumbs">
                        @include('partials.breadcrumbs-ar')
                    </div>
                    <h1 class="short-title">{{ $page->name_ar }}</h1>
                    {!! $page->content_ar !!}
                    <br/>
                </div>
            </div>
        </div>
    </div>

        <div class="container text-center">
            <div class="body-section alphabet-list">
                <div class="row">
                    <div class="col-md-2">
                        <ul class="en">
                            @foreach($letters['en'] as $letter)
                                <li>{{ $letter }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="col-md-8">
                        <div class="alphabet-list-content">


                            @foreach($letters['en'] as $letter)
                                <ul class="en" id="{{$letter}}">
                                    @if(isset($data_en[$letter]))
                                        @foreach($data_en[$letter] as $item)
                                            <li><a href="{{$item['link']}}">{{ $item['name'] }}</a></li>
                                        @endforeach
                                    @endif
                                </ul>
                            @endforeach

                            @foreach($letters['ar'] as $letter)
                                <ul class="ar" id="{{$letter}}">
                                    @if(isset($data_ar[$letter]))
                                        @foreach($data_ar[$letter] as $item)
                                            <li><a href="contributors/{{$item['slug']}}">{{ $item['name'] }}</a></li>
                                        @endforeach
                                    @endif
                                </ul>
                            @endforeach

                        </div>
                    </div>
                    <div class="col-md-2">
                        <ul class="ar letters">
                            @foreach($letters['ar'] as $letter)
                                <li>{{ $letter }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')
    <script>
        $('.alphabet-list ul li').on('click',function(){
            $('.alphabet-list-content ul').removeClass('active');
            $('.alphabet-list li').removeClass('active');
            $('#'+$(this).html()).addClass('active');

            if($(window).outerWidth()>767){
                height = $(this).height()+ 6;
                margin = parseInt($(this).css('margin-bottom'));
                targetList = $(this).closest('ul').hasClass('en') ? $('.alphabet-list ul.en li') : $('.alphabet-list .letters li');
                mtop = (margin + height) * ( targetList.index($(this)));
                $('#'+$(this).html()).css('margin-top',mtop);
            }
            $(this).addClass('active');
        });
    </script>
@endsection

resources/views/pages/form.blade.php
@extends('pages.master')

@section('content')
    <div class="innerpage">
        <div class="container text-center">
            <div class="body-section contents with-img-header">
                <div class="row" dir="">
                    <div class="col-md-12 ">
                        @if($data)
                            @include('partials.form')
                        @else
                            <h1 class="alert-danger alert">Article not found.</h1>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/publication.blade.php
@extends('pages.master')

@section('content')
    <div class="innerpage">
        <div class="container text-center">
            <div class="body-section contents with-img-header">
                <div class="row" dir="rtl">
                    @if(isset($_GET['lang']))
                        @if($_GET['lang']=='ar')
                            <div class="col-md-12 text-right">
                                <div class="breadcrumbs">
                                    @include('partials.breadcrumbs-ar')
                                </div>
                                <h1>{!!  $post->title_ar !!}</h1>
                                <h3 class="ar">{!! $post->author_ar !!}</h3>
                                <h3 class="ar">{!! $post->publication_ar !!}</h3>
                                @if(!count($post->sliders))
                                    {!! $post->content_ar !!}
                                @endif
                            </div>
                        @endif
                    @else
                        <div class="col-md-12 text-left">
                            <div class="breadcrumbs en">
                                @include('partials.breadcrumbs')
                            </div>
                            <h1 class="en">{!! $post->title !!}</h1>
                            <h3 class="en">{!! $post->author !!}</h3>
                            <h3 class="en">{!! $post->publication !!}</h3>
                            @if(!count($post->sliders))
                                {!! $post->content !!}
                            @endif
                        </div>
                    @endif
                </div>
            </div>
        </div>

        @if(count($post->sliders))
            <?php $page = $post; ?>
                @if(count($page->sliders)>0)
                <div class="container text-center">
                    <div class="body-section contents with-img-header">

                        @if(count($page->sliders)>1)
                            mama
                            <div class="owl-carousel-holder">
                                <div class="arrows">
                                    <button class="prev float-left"></button>
                                    <button class="next float-right"></button>
                                </div>
                                <div class="owl-carousel owl-theme">
                                    @foreach($page->sliders as $slide)
                                        mama
                                        @if($page->parent->slug=="partners")
                                            @if($slide->original)
                                                <div class="item">
                                                    <img src="{{ url('public/'.$slide->original->url) }}" data-en="{{ $slide->original->caption }}" data-ar="{{ $slide->original->caption_ar }}">
                                                </div>
                                            @endif
                                        @else
                                            @if($slide->landscape)
                                                <div class="item">
                                                    <img src="{{ url('public/'.$slide->landscape->url) }}" data-en="{{ $slide->landscape->caption }}" data-ar="{{ $slide->landscape->caption_ar }}">
                                                </div>
                                            @endif
                                        @endif
                                    @endforeach
                                </div>
                                <div id="owl-caption"></div>
                                <div id="owl-dots"></div>
                            </div>
                        @endif

                        <div class="row" dir="rtl">
                            @if(count($page->sliders)==1)
                                <div class="col-md-12">
                                    @if($page->parent->slug=="partners")
                                        @if($page->slider->original)
                                            <img src="{{ url('public/'.$page->slider->original->url) }}" width="100%">
                                            <span class="imgcap">
                                    <span class="en float-left">{{ $page->slider->original->caption }}</span>
                                    <span dir="rtl" class="float-right">{{ $page->slider->original->caption_ar }}</span>
                                </span>
                                        @endif
                                    @else
                                        @if($page->slider->landscape)
                                            <img src="{{ url('public/'.$page->slider->landscape->url) }}" width="100%" class="featured-img">
                                            <span class="imgcap">
                                    <span class="en float-left">{{ $page->slider->landscape->caption }}</span>
                                    <span dir="rtl" class="float-right">{{ $page->slider->landscape->caption_ar }}</span>
                                </span>
                                        @endif
                                    @endif


                                    <br/>
                                    <br/>
                                </div>
                            @endif

                            @if(isset($_GET['lang']))
                                @if($_GET['lang']=='ar')
                                    <div class="col-md-12 text-right">
                                        {!! $page->content_ar !!}
                                    </div>
                                @endif
                            @else
                                <div class="col-md-12 text-left">
                                    {!! $page->content !!}
                                </div>
                            @endif

                        </div>
                    </div>
                </div>
            @endif
        @endif

        @if($post->additional_content_bottom)
            <div class="container text-center">
                <div class="body-section contents with-img-header">
                    <div class="row" dir="rtl">
                        <div class="col-md-12 text-left">
                            {!! $post->additional_content_bottom !!}
                        </div>
                    </div>
                </div>
            </div>
        @endif

        @if($formdata)
            <div class="container text-center">
                <div class="body-section contents">
                    @include('partials.form')
                </div>
            </div>
        @endif

        @if($post->buttonLinks)
            <div class="container text-center">
                <div class="body-section contents">
                    <div class="row" dir="rtl">
                        <div class="col-md-6 text-right">
                            @if($post->buttonLinks->title && $post->buttonLinks->value)
                                <a href="{{$post->buttonLinks->value_ar}}"><input type="submit" class="ar" value="{{ $post->buttonLinks->title_ar }}"></a>
                            @endif
                        </div>
                        <div class="col-md-6 text-left">
                            @if($post->buttonLinks->title && $post->buttonLinks->value)
                                <a href="{{$post->buttonLinks->value}}"><input type="submit" class="en" value="{{ $post->buttonLinks->title }}"></a>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        @endif

    </div>
@endsection

resources/views/pages/search.blade.php
@extends('pages.master')

@section('css')
    <link rel="stylesheet" href="{{ asset('public/css/search.css') }}">
@endsection

@section('content')
    <div class="innerpage">
        <div class="container text-center">
            <div class="body-section contents">
                <div class="row" dir="rtl">
                    <div class="col-md-6 text-right">
                        <h1>نتائج البحث</h1>
                    </div>
                    <div class="col-md-6 text-left">
                        <h1>SEARCH RESULT</h1>
                    </div>
                </div>
            </div>
            <div class="body-section contents">
                <div class="row" dir="rtl">
                    <div class="col-md-12 text-left">
                        <form action="{{ url('search') }}" method="post">
                            <input type="hidden" value="{!! csrf_token() !!}" name="_token">
                            <input type="text" id="searchbox" name="keyword" value="{{$keyword}}">
                            <input type="submit" id="searchbt" value="">
                        </form>
                    </div>
                </div>
            </div>
            <div class="body-section contents">
                <div class="row" dir="rtl">
                    <div class="col-md-12 text-left">
                        <label>Your search query for ‘{{$keyword}}’ returned the following  matches:</label>
                        <ul style="width:100%;">
                            <li><a href="#"> </a></li>
                            @foreach($data['pages'] as $item)
                                <li><a href="{{url($item->link)}}">{{$item->name}}</a></li>
                            @endforeach
                            @foreach($data['posts'] as $item)
                                <li><a href="{{url($item->link)}}">{{$item->title}}</a></li>
                            @endforeach
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection